name: Update Latest Version

on:
  push:
    tags:
      - "v*"

jobs:
  update-latest:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "${GITHUB_REF_NAME}" > VERSION
      - run: |
          git config user.name "bot"
          git config user.email "bot@quicksi.io"
          git add VERSION
          git commit -m "update VERSION"
          git push